name: ufc
channels:
  - conda-forge  # prioritize packages from conda-forge repositories
  - defaults
dependencies:
  - python>=3.7,<=3.9  # version of Python, there are minimum requirements on version, we leave it up to conda
  - pip  # a package taken from conda repository
  - matplotlib
  - numpy
  - notebook
  - pandas
  - scikit-learn
  - requests
  - seaborn
  - pip:
      - see  # an example of package installed using pip as it is not available on conda
